### ISSUE TITLE
Tolerance difference between biorbd-casadi and biorbd-eigen for RT check

### ISSUE THREAD

**Issue by vennand** [pyomeca/biorbd#169]
Error when trying to use `BiorbdViz.BiorbdViz(model_path)` with biorbd-eigen. No error when biorbd-casadi is used instead.

```
Traceback (most recent call last):
  File "/snap/pycharm-community/209/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/andre/anaconda3/envs/KalmanFilter/lib/python3.8/site-packages/BiorbdViz/__init__.py", line 292, in __init__
    if sum([len(i) for i in self.model.meshPoints(np.zeros(self.model.nbQ()))]) > 0:
  File "/home/andre/anaconda3/envs/KalmanFilter/lib/python3.8/site-packages/biorbd/biorbd.py", line 3630, in meshPoints
    return _biorbd.Joints_meshPoints(self, *args)
RuntimeError: The Rotation matrix norm is not equal to one
```

Tolerance is probably too strict in biorbd-eigen.
If biorbd is compiled from source while setting SKIP_ASSERT to TRUE using CMAKE, no error is found.
Error occurs using a model with 42 DoFs, 17 segments and 95 markers.

**Comment by pariterre** [comment]
The PR #170  Reduced the tolerance for the Rotation matrix norm 
Thanks for reporting!
